export const data = [
  {
    productId: 1,
    productName: "Kale Caesar",
    productCategory: "Salad",
    productImage: "/cesar.jpg",
    productDescription: "Roasted chicken, tomatoes, parmesan crisps, shaved parmesan, shredded kale, chopped romaine, lime squeeze, caesar",
    productOldPrice: 100,
    productNewPrice: 1000,
    productWeight: 400,
  },
  {
    productId: 2,
    productName: "Kale Caesar",
    productCategory: "Salad",
    productImage: "/cesar.jpg",
    productDescription: "Roasted chicken, tomatoes, parmesan crisps, shaved parmesan, shredded kale, chopped romaine, lime squeeze, caesar",
    productOldPrice: 0,
    productNewPrice: 1000,
    productWeight: 400,
  },
  {
    productId: 3,
    productName: "Kale Caesar",
    productCategory: "Salad",
    productImage: "/cesar.jpg",
    productDescription: "Roasted chicken, tomatoes, parmesan crisps, shaved parmesan, shredded kale, chopped romaine, lime squeeze, caesar",
    productOldPrice: 0,
    productNewPrice: 1000,
    productWeight: 400,
  },
  {
    productId: 4,
    productName: "Kale Caesar",
    productCategory: "Salad",
    productImage: "/cesar.jpg",
    productDescription: "Roasted chicken, tomatoes, parmesan crisps, shaved parmesan, shredded kale, chopped romaine, lime squeeze, caesar",
    productOldPrice: 0,
    productNewPrice: 1000,
    productWeight: 400,
  },
  {
    productId: 5,
    productName: "Kale Caesar",
    productCategory: "Salad",
    productImage: "/cesar.jpg",
    productDescription: "Roasted chicken, tomatoes, parmesan crisps, shaved parmesan, shredded kale, chopped romaine, lime squeeze, caesar",
    productOldPrice: 0,
    productNewPrice: 1000,
    productWeight: 400,
  },
  {
    productId: 6,
    productName: "Kale Caesar",
    productCategory: "Salad",
    productImage: "/cesar.jpg",
    productDescription: "Roasted chicken, tomatoes, parmesan crisps, shaved parmesan, shredded kale, chopped romaine, lime squeeze, caesar",
    productOldPrice: 0,
    productNewPrice: 1000,
    productWeight: 400,
  },
];
